### PR TITLE
Fix: Choose default language

### PR DESCRIPTION
**Pull request by roottool**
## Issue number

#2 

## Description

This PR adds a logic to choose default language.
I use [iso-639-1](https://www.npmjs.com/package/iso-639-1).

## Screenshot

ChooseDefaultLanguage
**※My default language is Japanese.**

### CODE REVIEW

**Comment by glkwhr** [comment]
Thanks for the pull request! Generally looks good but it seems `iso-639-1` only supports 2-letter code? 

For example `ja` can be recognized but `ja-jp` can't. 

FYI - `navigator.language` results from previous visitors (ordered by amount):
image

**Comment by roottool** [comment]
Thank you for review!
Yes, `iso-639-1` recognizes only language code like `ja`.
Therefore, I added [locale-code](https://www.npmjs.com/package/locale-code).
`locale-code` recognizes only `language code-country code` like `ja-JP`.
I added a logic which `locale-code` gets a language name if `iso-639-1` can't get a language name.

**Comment by roottool** [comment]
I found the problem,
This logic cant't recognize Taiwanese.
Because `locale-code` recognizes `zh-TW` as Chinese.
Probably, I have to add a new logic like the below.

```ts
if (languageCode === 'zh-TW') {
  languageName = 'taiwanese';
}
```

**Comment by glkwhr** [comment]
LGTM. It seems in-game data doesn't completely follow the iso. I'll add the logic later. Thanks for the fix!

**Pull request merged**
